name: 'Provision gardener'
description: 'Create a gardener cluster'
inputs:
  gardener_server:
    description: 'Gardener api server address'
    required: true
  gardener_token:
    description: 'Gardener token used to authenticate'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Checkout to PR branch # to remove after getting rid of pull_request_target
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      run: |
        git fetch origin pull/${{ github.event.number }}/head:PR-${{ github.event.number }}
        git checkout PR-${{ github.event.number }}
    - name: Create Gardener Cluster
      shell: bash
      env:
        GARDENER_SERVER: ${{ inputs.gardener_server }}
        GARDENER_TOKEN: ${{ inputs.client_secret }}
      run: |
        ./hack/ci/gardener.sh
        curl -Lo kyma https://storage.googleapis.com/kyma-cli-unstable/kyma-linux
        chmod +x kyma
        ./kyma provision gardener aws \
            --secret "trial-secretbinding-aws" \
            --name "github-test" \
            --project "goatz" \
            --credentials "kubeconfig.yaml" \
            --region "eu-west-1" \
            -z "eu-west-1c" \
            -t "m5.large" \
            --disk-type "gp3" \
            --disk-size 50 \
            --scaler-max 2 \
            --scaler-min 1 \
            --kube-version="1.27.6" \
            --attempts 1 \
            --verbose \
            --hibernation-start "" \
            --gardenlinux-version "934.11.0"
